<a href="https://colab.research.google.com/github/Arhin-Eben/FUTURE_DS_01/blob/master/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

**THE BASICS**

In [2]:
a = np.array([1,2,3,4])
print(a)

[1 2 3 4]


In [3]:
b = np.array(([1,2,3,4,5], [2,4,6,9,1]))
print(b)

[[1 2 3 4 5]
 [2 4 6 9 1]]


In [4]:
b = b+10
print(b)

[[11 12 13 14 15]
 [12 14 16 19 11]]


In [5]:
#Get Dimension
a.ndim

1

In [6]:
b.ndim

2

In [7]:
#Get Shape
a.shape

(4,)

In [8]:
b.shape

(2, 5)

In [9]:
#Get Type
a.astype

<function ndarray.astype>

In [10]:
a.dtype

dtype('int64')

In [11]:
b.astype

<function ndarray.astype>

In [12]:
b.dtype

dtype('int64')

In [13]:
#Get size
a.size

4

In [14]:
a.itemsize

8

**ACCESSING/CHANGING SPECIFIC ELEMENTS,ROWS,COLUMNS,ETC**

In [15]:
d = np.array(([1,2,3,4,5], [2,4,6,8,1]))
print(d[0,2])

3


In [16]:
#Get a specific column
print(d[:, 2])

[3 6]


In [17]:
print(d[:, 4])

[5 1]


**INITIALIZING DIFFERENT TYPES OF ARRAYS**

In [19]:
#All 0s matrix
np.zeros(6)

array([0., 0., 0., 0., 0., 0.])

In [20]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [23]:
#All ones
np.ones((4,2,2))

array([[[1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.]]])

In [25]:
#All twos
np.full((2,2), 2)

array([[2, 2],
       [2, 2]])

In [27]:
#All threes
np.full((3,2), 3)

array([[3, 3],
       [3, 3],
       [3, 3]])

In [28]:
#Generating random numbers
np.random.rand(4,2)

array([[0.3834683 , 0.93974261],
       [0.15635347, 0.44971559],
       [0.76465632, 0.34528256],
       [0.96452898, 0.92336033]])

In [29]:
np.random.rand(4,2,3)

array([[[0.03089425, 0.60435524, 0.79533213],
        [0.77602717, 0.91538358, 0.28522603]],

       [[0.55896528, 0.50355481, 0.01275829],
        [0.21540371, 0.31036686, 0.14806473]],

       [[0.22174988, 0.20961849, 0.87213179],
        [0.17372289, 0.61841803, 0.23833679]],

       [[0.3848473 , 0.92227909, 0.83695126],
        [0.60468559, 0.78012855, 0.05357083]]])

In [59]:
#Generating random integer numbers
np.random.randint(3, 8, size=(3, 3))

array([[3, 4, 7],
       [3, 6, 7],
       [5, 5, 3]])

In [60]:
#Identity matrix
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

**MATHEMATICS**

In [64]:
p = np.array([10,20,30,40])
p = p/2
print(p)

[ 5. 10. 15. 20.]


In [65]:
q = np.array([10,20,30,40])
q = q+2
print(q)

[12 22 32 42]


In [66]:
i = np.array([1,2,3,4])
v = np.array([5,6,7,8])
print(i*v)

[ 5 12 21 32]
