<a href="https://colab.research.google.com/github/Arhin-Eben/Machine-learning-with-python/blob/master/PyTorch_GradientCalculation.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

** Gradient Calculation With Autograd**

In [2]:
import torch

x= torch.randn(3,requires_grad=True)
print(x)

y = x+2
print(y)

z = y*y*2
print(z)

z = z.mean()
print(z)

z.backward() #dz/dx
print(x.grad)

v = torch.tensor([0.1,1.0,0.001],dtype=torch.float32)
z.backward(v) #dz/dx
print(x.grad)

tensor([ 1.0305, -1.3686,  0.4789], requires_grad=True)
tensor([3.0305, 0.6314, 2.4789], grad_fn=<AddBackward0>)
tensor([18.3676,  0.7974, 12.2896], grad_fn=<MulBackward0>)
tensor(10.4849, grad_fn=<MeanBackward0>)
tensor([4.0406, 0.8419, 3.3052])


In [3]:
# x.requires_grad_(False)
x.requires_grad_(False)
print(x)

#x.detouch()
y = x.detach()
print(y)

#with torch.no_grad():
with torch.no_grad():
  y = x+2
  print(y)

tensor([ 1.0305, -1.3686,  0.4789])
tensor([ 1.0305, -1.3686,  0.4789])
tensor([3.0305, 0.6314, 2.4789])


In [6]:
#Just some dummy example
weights = torch.ones(4,requires_grad=True)

for epoch in range(3):
  model_output = (weights*3).sum()

  model_output.backward()

  print(weights.grad)

  weights.grad.zero_()


tensor([3., 3., 3., 3.])
tensor([3., 3., 3., 3.])
tensor([3., 3., 3., 3.])


In [ ]:
#Optimizer
optimizer = torch.optim.SGD(weights,lr=0.01)
optimizer.step()
optimizer.zero_grad()