<a href="https://colab.research.google.com/github/Arhin-Eben/Machine-learning-with-python/blob/master/Pytorch_Basics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch as tc

#create empty tensor
x = tc.empty(3)
print(x)

tensor([0., 0., 0.])


In [2]:
#create 2D tensor
y = tc.empty(2,3)
print(y)

tensor([[-2.7590e-33,  4.5118e-41, -2.7590e-33],
        [ 4.5118e-41,  1.5414e-44,  0.0000e+00]])


In [3]:
#create 3D tensor
y = tc.empty(2,2,3)
print(y)

tensor([[[ 0.0000e+00,  0.0000e+00,  0.0000e+00],
         [ 0.0000e+00,  1.3672e-38,  0.0000e+00]],

        [[ 9.1084e-44,  0.0000e+00,  2.0541e-01],
         [ 0.0000e+00, -3.2758e-31,  4.5119e-41]]])


In [4]:
#Create tensor filled with all ones
ones = tc.ones(2,2,3)
print(ones)

tensor([[[1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.]]])


In [5]:
#Create tensor filled with twos
twos = tc.full((2,2,2,3), 2)
print(twos)

tensor([[[[2, 2, 2],
          [2, 2, 2]],

         [[2, 2, 2],
          [2, 2, 2]]],


        [[[2, 2, 2],
          [2, 2, 2]],

         [[2, 2, 2],
          [2, 2, 2]]]])


In [6]:
#create tensor with random values
x = tc.rand(2,2)
y = tc.rand(2,2)
print(x)
print(y)

#Add the random numbers
z = x + y
print(z)

#Subtract them
a = x - y
print(a)

#Multiply them
b = x * y
print(b)

#Divide them
c = x / y
print(c)

tensor([[0.6392, 0.9301],
        [0.4977, 0.6393]])
tensor([[0.8979, 0.8754],
        [0.1296, 0.8104]])
tensor([[1.5372, 1.8055],
        [0.6273, 1.4497]])
tensor([[-0.2587,  0.0548],
        [ 0.3681, -0.1710]])
tensor([[0.5740, 0.8142],
        [0.0645, 0.5181]])
tensor([[0.7119, 1.0626],
        [3.8401, 0.7889]])


In [7]:
#Slicing in random

x = tc.rand(5, 3)
print(x)
print(x[1, 1].item())

tensor([[0.4028, 0.7135, 0.3367],
        [0.8500, 0.3426, 0.4042],
        [0.1017, 0.0099, 0.8234],
        [0.9902, 0.0172, 0.6958],
        [0.9941, 0.1554, 0.5423]])
0.34259891510009766


In [8]:
#Random with views
x = tc.rand(4, 4)
print(x)

tensor([[0.7320, 0.2181, 0.5677, 0.6040],
        [0.0467, 0.5084, 0.4720, 0.7961],
        [0.6489, 0.8702, 0.9189, 0.0246],
        [0.3550, 0.9335, 0.4174, 0.4091]])


In [9]:
x = tc.rand(4, 4)
print(x)
y = x.view(16)
print(y)

tensor([[0.5487, 0.1815, 0.9207, 0.0661],
        [0.5915, 0.1387, 0.9559, 0.2559],
        [0.3622, 0.3039, 0.2963, 0.2983],
        [0.6567, 0.3436, 0.0522, 0.6568]])
tensor([0.5487, 0.1815, 0.9207, 0.0661, 0.5915, 0.1387, 0.9559, 0.2559, 0.3622,
        0.3039, 0.2963, 0.2983, 0.6567, 0.3436, 0.0522, 0.6568])


In [10]:
y = x.view(-1, 8)
print(y)

tensor([[0.5487, 0.1815, 0.9207, 0.0661, 0.5915, 0.1387, 0.9559, 0.2559],
        [0.3622, 0.3039, 0.2963, 0.2983, 0.6567, 0.3436, 0.0522, 0.6568]])


In [11]:
y = x.view(-1, 16)
print(y.size())

torch.Size([1, 16])


In [15]:
#
import numpy as np

a = tc.ones(5)
print(a)

#printing the ones as array
b = a.numpy()
print(b)

tensor([1., 1., 1., 1., 1.])
[1. 1. 1. 1. 1.]
